package com.chaitanya.schoolmanagement.ui.forms.exam.view;

import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import javax.swing.*;

@Component
@Getter
@Slf4j
public class ViewQuestionForm extends JFrame {

    // Variables declaration - do not modify
    private JButton backBtn;
    private JLabel bgImageLbl;
    private JLabel correctANswerLbl;
    private JTextField correctAnsTF;
    private JButton deleteBtn;
    private JButton jButton1;
    private JLabel jLabel3;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JScrollPane jScrollPane1;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField optionFourTF;
    private JLabel optionOneLbl;
    private JTextField optionOneTF;
    private JTextField optionOneTF1;
    private JLabel optionThreeLbl;
    private JTextField optionThreeTF;
    private JLabel optionTwoLbl;
    private JTextField optionTwoTF;
    private JLabel quesNoLbl;
    private JTextField quesNoTF;
    private JLabel questionLbl;
    private JTextArea questionTA;
    private JButton updateBtn;
    private JLabel viewQuestionLbl;
    // End of variables declaration

    /**
     * Creates new form ViewQuestionSchool
     */
    public ViewQuestionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        optionOneTF1 = new JTextField();
        jButton1 = new JButton();
        bgImageLbl = new JLabel();
        viewQuestionLbl = new JLabel();
        jScrollPane1 = new JScrollPane();
        questionTA = new JTextArea();
        questionLbl = new JLabel();
        optionOneLbl = new JLabel();
        optionTwoLbl = new JLabel();
        jLabel6 = new JLabel();
        optionThreeLbl = new JLabel();
        jLabel7 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        optionOneTF = new JTextField();
        optionTwoTF = new JTextField();
        optionThreeTF = new JTextField();
        optionFourTF = new JTextField();
        correctANswerLbl = new JLabel();
        correctAnsTF = new JTextField();
        jLabel3 = new JLabel();
        quesNoLbl = new JLabel();
        quesNoTF = new JTextField();
        updateBtn = new JButton();
        deleteBtn = new JButton();
        backBtn = new JButton();

        optionOneTF1.setEditable(false);

        jButton1.setIcon(new ImageIcon("/Images/Webp.net-resizeimage (3).png")); // NOI18N
        jButton1.setText("Edit");


        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        bgImageLbl.setIcon(new ImageIcon("/Images/quiz_m.jpg")); // NOI18N
        bgImageLbl.setText("jLabel9");

        viewQuestionLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewQuestionLbl.setForeground(new java.awt.Color(255, 255, 255));
        viewQuestionLbl.setText("VIEW QUESTIONS");

        questionTA.setEditable(false);
        questionTA.setColumns(20);
        questionTA.setRows(5);
        jScrollPane1.setViewportView(questionTA);

        questionLbl.setText("Question");

        optionOneLbl.setForeground(new java.awt.Color(255, 255, 255));
        optionOneLbl.setText("Option One");

        optionTwoLbl.setForeground(new java.awt.Color(255, 255, 255));
        optionTwoLbl.setText("Option Two");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Answer Three");

        optionThreeLbl.setForeground(new java.awt.Color(255, 255, 255));
        optionThreeLbl.setText("Option Three");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Option Four");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        optionOneTF.setEditable(false);

        optionTwoTF.setEditable(false);


        optionThreeTF.setEditable(false);

        optionFourTF.setEditable(false);

        correctANswerLbl.setForeground(new java.awt.Color(255, 255, 255));
        correctANswerLbl.setText("Correct Answer -");

        correctAnsTF.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ques_ID -");

        quesNoLbl.setForeground(new java.awt.Color(255, 255, 255));
        quesNoLbl.setText("Ques No -");

        quesNoTF.setEditable(false);

        updateBtn.setIcon(new ImageIcon("/Images/Webp.net-resizeimage (4).png")); // NOI18N
        updateBtn.setText("Update");


        deleteBtn.setIcon(new ImageIcon("/Images/Webp.net-resizeimage (2).png")); // NOI18N
        deleteBtn.setText("Delete");


        backBtn.setText("Back");


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(viewQuestionLbl))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(22, 22, 22)
                                                        .addComponent(questionLbl, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(quesNoLbl, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(quesNoTF, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 570, GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(correctANswerLbl)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(correctAnsTF, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(optionTwoLbl)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(optionTwoTF, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(optionFourTF, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(optionThreeLbl)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(optionThreeTF, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(optionOneLbl)
                                                                                .addGap(70, 70, 70)
                                                                                .addComponent(optionOneTF, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(48, 48, 48)
                                                                        .addComponent(updateBtn)
                                                                        .addGap(29, 29, 29)
                                                                        .addComponent(deleteBtn, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(backBtn, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))))))
                                .addContainerGap(16, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(bgImageLbl, GroupLayout.PREFERRED_SIZE, 600, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(251, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addContainerGap(251, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(172, Short.MAX_VALUE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(172, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(viewQuestionLbl)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(questionLbl)
                                        .addComponent(quesNoLbl)
                                        .addComponent(quesNoTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(optionOneLbl)
                                        .addComponent(optionOneTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(optionTwoTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(optionTwoLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(optionThreeTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(optionThreeLbl))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(optionFourTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(correctANswerLbl)
                                        .addComponent(correctAnsTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(updateBtn)
                                        .addComponent(deleteBtn)
                                        .addComponent(backBtn))
                                .addGap(19, 19, 19))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(bgImageLbl, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(258, Short.MAX_VALUE)
                                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(242, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(238, Short.MAX_VALUE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(239, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        


}
